---
apiVersion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  type: ClusterIP
  selector:
    app: dbdeployment
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: phpsvc
spec:
  type: NodePort
  selector:
    app: phpdeployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
